---
AbcMetricMethodCheck:           
  score: 7.3
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 260 }
ClassNameCheck:                  
  pattern: !ruby/regexp /\A(?:GridFS|[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 1 }
CyclomaticComplexityMethodCheck: { complexity: 2 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
MethodLineCountCheck:            { line_count: 10 }
MethodNameCheck:                 
  pattern: !ruby/regexp /\A(?:[a-z\d](?:_?[a-z\d])+[?!=]?|\[\]=?|==|<=>|<<|[+*&|-])\z/
ModuleLineCountCheck:            { line_count: 262 }
ModuleNameCheck:                 
  pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/
ParameterNumberCheck:            { parameter_count: 3 }
